site:
  title: PierreR (pi3r)
  url: https://pi3r.be
  start_page: notebook::nix/index.adoc
content:
  sources:
  - url: https://github.com/pierrer/notebook.git
    branches: master
  - url: https://github.com/CIRB/devbox.git
    start_path: docs
    branches: master
ui:
  bundle:
    url: https://github.com/PierreR/antora-ui/releases/download/v0.5/ui-bundle.zip
  supplemental_files: ./supplemental-ui
