site:
  title: ğ›‘3r
  url: https://pi3r.be
  start_page: notebook::nix/index.adoc
content:
  sources:
  - url: https://github.com/pierrer/notebook.git
    branches: master
asciidoc:
  attributes:
    experimental: ''
    example-caption: ~
    table-caption: ~
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
