site:
  title: 𝛑3r
  url: https://pi3r.be
  start_page: notebook::nix/index.adoc
content:
  sources:
  - url: https://github.com/pierrer/notebook.git
    branches: master
  - url: https://github.com/pierrer/devbox.git
    start_path: docs
    branches: master
asciidoc:
  attributes:
    example-caption: ~
ui:
  bundle:
    url: https://github.com/PierreR/antora-ui/releases/download/v0.6b/ui-bundle.zip
  supplemental_files: ./supplemental-ui
